import localFont from "next/font/local";
import "./globals.css";
import { QueryProvider } from "./apis/query-provider/QueryProvider";
import Navbar from "./components/Navbar";
import { Suspense } from "react";
import Loading from "./loading";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // console.log(process.env.NEXT_PUBLIC_FRONT_API)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <Suspense fallback={<Loading/>}>
            <Navbar/>
            {children}
          </Suspense>
        </QueryProvider>
      </body>
    </html>
  );
}
